version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
    groups:
      bundler-minor-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/frontend/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "nuxt"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
