services:
  db:
    image: postgres:15
    container_name: playbeta_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DB}
    volumes:
      - playbeta-db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playbeta_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - playbeta-bundle:/usr/local/bundle
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    command: sh -c "rm -f /rails/tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: playbeta_frontend
    ports:
      - "3001:3001"
      - "24678:24678"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
    environment:
      NODE_ENV: development

volumes:
  playbeta-db-data:
  playbeta-bundle:
