services:
  db:
    image: postgres:15
    container_name: playbeta_db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - playtest-db-data:/var/lib/postgresql/data

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: playbeta_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/nuxt
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:3000

volumes: 
  playtest-db-data:
